sudo: required
services:
  - docker

script:
  - docker build -t liu026/node .
  - docker images liu026/node

before_deploy:
 -docker login -u liu026 -p 3670577pL

deploy:
  provider: script
  script: docker push liu026/node
  on:
    branch: master